###############
## 
####

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'Deblurring'
  SESSION: 'SDAN-MD'

OPTIM:
  BATCH_SIZE: 1
  NUM_EPOCHS: 400
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-5
  LR_MIN: 1e-8
  # BETA1: 0.9


#TRAINING:
#  VAL_AFTER_EVERY: 1
#  RESUME: False
#  TRAIN_PS: 240
#  VAL_PS: 240
#  TRAIN_DIR: '/data' # path to training data
#  VAL_DIR: '/data'    # path to validation data
#  TRAIN_VAL_DIR: '/data'    # path to validation data
#  SAVE_DIR: '/save'     # path to save models and images
#  # SAVE_IMAGES: False

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 240
  VAL_PS: 240
  TRAIN_DIR: 'D:/Dataset/KITTI/MPRNet/psf_30_kitti_firstfold/train' # path to training data
  VAL_DIR: 'D:/Dataset/KITTI/MPRNet/psf_30_kitti_firstfold/test'    # path to validation data
  TRAIN_VAL_DIR: 'D:/Dataset/KITTI/MPRNet/psf_30_kitti_firstfold/val'    # path to validation data
  SAVE_DIR: 'E:/scd'     # path to save models and images
  # SAVE_IMAGES: False